services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: application
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  
  migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: migration
    volumes:
      - .:/usr/app
    env_file:
      - .env
    depends_on:
      - db
      - app
    networks:
      - app-network
    
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
